import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  envelopeOf,
  importV0,
  migrateDocument,
  unseal,
  deriveKey,
  seal,
  randomSalt,
} from '../../src/kernel/index';

// Envelope interop with reference/adnotia-v0-monolith.html.
//
// docs/06-data-model.md says the envelope format is unchanged between v0 and v1,
// and that an encrypted old key "is decrypted with the passcode first". This
// proves it both ways rather than assuming it: the monolith's own crypto is
// lifted out of the file and run.
//
// Note on what this does and does not show. No real v0 document was available,
// so the ciphertext here is generated by the monolith rather than taken from a
// person's browser. That covers the format exactly; it cannot cover whatever a
// real stored document might have accumulated.

const monolith = readFileSync(
  resolve(process.cwd(), 'reference/adnotia-v0-monolith.html'),
  'utf8',
);

function extract(name: string): string {
  const start = monolith.indexOf(`function ${name}(`);
  if (start === -1) throw new Error(`The monolith has no function ${name}`);
  let depth = 0;
  for (let i = monolith.indexOf('{', start); i < monolith.length; i++) {
    if (monolith[i] === '{') depth++;
    else if (monolith[i] === '}') {
      depth--;
      if (depth === 0) return monolith.slice(start, i + 1);
    }
  }
  throw new Error(`Unbalanced braces in ${name}`);
}

interface MonolithCrypto {
  toB64: (buf: ArrayBuffer | Uint8Array) => string;
  fromB64: (s: string) => Uint8Array;
  randBytes: (n: number) => Uint8Array;
  deriveKey: (pass: string, salt: Uint8Array, iter?: number) => Promise<CryptoKey>;
  sealWith: (key: CryptoKey, salt: Uint8Array, plaintext: string, iter?: number) => Promise<string>;
  openWith: (key: CryptoKey, env: unknown) => Promise<string>;
  envelopeOf: (raw: string) => unknown;
}

const NAMES = ['toB64', 'fromB64', 'randBytes', 'deriveKey', 'sealWith', 'openWith', 'envelopeOf'];

/** The monolith's crypto, with its `window` and `ITER` supplied. */
function monolithCrypto(iterations: number): MonolithCrypto {
  const source = NAMES.map(extract).join('\n');
  const build = new Function(
    'window',
    'ITER',
    `${source}\nreturn { ${NAMES.join(', ')} };`,
  ) as (w: unknown, iter: number) => MonolithCrypto;
  return build(globalThis, iterations);
}

const FAST = 1000;
const v0 = monolithCrypto(FAST);

describe('envelope interop with the monolith', () => {
  it('lifted the monolith’s crypto', () => {
    expect(typeof v0.sealWith).toBe('function');
    expect(typeof v0.openWith).toBe('function');
  });

  it('opens what the monolith sealed', async () => {
    const salt = v0.randBytes(16);
    const key = await v0.deriveKey('123456', salt, FAST);
    const sealed = await v0.sealWith(key, salt, '{"entries":{}}', FAST);

    const envelope = envelopeOf(sealed);
    expect(envelope).not.toBeNull();
    expect(await unseal('123456', envelope!)).toBe('{"entries":{}}');
  });

  it('the monolith opens what we sealed', async () => {
    const salt = randomSalt();
    const key = await deriveKey('123456', salt, FAST);
    const sealed = await seal(key, salt, '{"schemaVersion":1}', FAST);

    const theirKey = await v0.deriveKey('123456', salt, FAST);
    expect(await v0.openWith(theirKey, JSON.parse(sealed))).toBe('{"schemaVersion":1}');
  });

  it('agrees on what an envelope looks like', async () => {
    const salt = randomSalt();
    const sealed = await seal(await deriveKey('123456', salt, FAST), salt, 'x', FAST);
    // Their detector accepts ours, and ours accepts theirs.
    expect(v0.envelopeOf(sealed)).not.toBeNull();

    const theirSalt = v0.randBytes(16);
    const theirSealed = await v0.sealWith(
      await v0.deriveKey('123456', theirSalt, FAST),
      theirSalt,
      'x',
      FAST,
    );
    expect(envelopeOf(theirSealed)).not.toBeNull();
  });

  it('agrees a plain document is plain', () => {
    expect(v0.envelopeOf('{"entries":{}}')).toBeNull();
    expect(envelopeOf('{"entries":{}}')).toBeNull();
  });

  it('imports an encrypted v0 document once it is unsealed', async () => {
    // The whole path docs/06-data-model.md describes: an old key holding an
    // envelope, decrypted with the passcode, then migrated.
    const original = {
      entries: {
        '2026-09-04': {
          date: '2026-09-04',
          med: 'Elvanse',
          dose: '50',
          unit: 'mg',
          times: ['08:00'],
          focus: 4,
          bed: '23:40',
          wake: '07:00',
          sleep: '7.25',
          win: 'Got out on time',
          createdAt: '2026-09-04T21:30:00.000Z',
        },
      },
      questions: [],
      baseline: { focus: 2, mood: 2, sleep: '6', note: '' },
      lastBackup: '',
      lastAppt: '',
      overall: '',
    };

    const salt = v0.randBytes(16);
    const key = await v0.deriveKey('123456', salt, FAST);
    const storedUnderOldKey = await v0.sealWith(key, salt, JSON.stringify(original), FAST);

    // Nothing readable sits in storage.
    expect(storedUnderOldKey).not.toContain('Elvanse');

    const plaintext = await unseal('123456', envelopeOf(storedUnderOldKey)!);
    const imported = migrateDocument(JSON.parse(plaintext));

    expect(imported.schemaVersion).toBe(1);
    expect(imported.kernel.enabledModules).toEqual(['medication', 'sleep']);
    const days = imported.modules['medication']?.['days'] as Record<string, Record<string, unknown>>;
    expect(days['2026-09-04']?.['med']).toBe('Elvanse');
    expect(imported.kernel.days['2026-09-04']?.win).toBe('Got out on time');

    // And the direct route agrees with going through migrateDocument.
    expect(importV0(JSON.parse(plaintext)).document.modules).toEqual(imported.modules);
  });
});
